#docker installation
- name: install docker.io
  action: apt pkg=docker.io state=installed
- name: install docker-py
  pip:  name=docker-py version=0.3.0

- name: restart docker.io
  service: 
    name: docker.io 
    state: restarted


