#docker installation
- name: install docker.io
  action: apt pkg=docker.io state=installed
- name: install docker-py
  pip:  name=docker-py version=0.3.0

- name: install nsenter
  command: docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter


#これやばい
#- name: restart docker.io
#  service: 
#    name: docker.io 
#    state: restarted


