#docker installation
- name: check lxc-docker installed
  command: dpkg-query -l lxc-docker
  register: docker_installed
  changed_when: False
  ignore_errors: True
  always_run: yes

- name: install docker.io
  shell: wget -qO- https://get.docker.com/ | sh
  when: docker_installed|failed

- name: install docker-py
  pip:  name=docker-py version=1.1.0


- name: check nsenter
  shell: sudo docker images | grep -q "jpetazzo/nsenter"
  register: nsenter_installed
  changed_when: false
  ignore_errors: True
  always_run: yes
- name: install nsenter
  command: docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
  when: nsenter_installed|failed


